apiVersion: v1
kind: Service
metadata:
  name: moviemng
  labels:
    app: moviemng
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: moviemng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviemng
  labels:
    app: moviemng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviemng
  template:
    metadata:
      labels:
        app: moviemng
    spec:
      containers:
        - name: moviemng
          image: hi3293/moviemng
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5