apiVersion: v1
kind: Service
metadata:
  name: seatmng
  labels:
    app: seatmng
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: seatmng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatmng
  labels:
    app: seatmng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatmng
  template:
    metadata:
      labels:
        app: seatmng
    spec:
      containers:
        - name: seatmng
          image: hi3293/seatmng
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5