server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      auto-ddl: update
      use-new-id-generator-mappings: false
    generate-ddl: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: mypage
          destination: moviereservationreport
          contentType: application/json
        event-out:
          destination: moviereservationreport
          contentType: application/json
  datasource:
    url: jdbc:mysql://database-2.cxbzaw0b0fi0.ap-northeast-2.rds.amazonaws.com/innodb
    username: admin
    password: hi591005
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8085
---
spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      auto-ddl: update
      use-new-id-generator-mappings: false
    generate-ddl: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: mypage
          destination: moviereservationreport
          contentType: application/json
        event-out:
          destination: moviereservationreport
          contentType: application/json
  datasource:
    url: jdbc:mysql://database-2.cxbzaw0b0fi0.ap-northeast-2.rds.amazonaws.com/innodb
    username: admin
    password:
